Update .version file for KSP 1.12.x compat
snjo/Firespitter pull request #228
Opened 2022-09-12 05:58 UTC by NathanKell

@BobPalmer Over the past year or so Firespitter has looked pretty solid on KSP 1.12, so it'd be awesome if the .version file allowed it to be installed by CKAN rather than requiring either (a) a manual install or (b) setting a compat flag in the CKAN client (which can do other weird things if other mods' versioning is weird).

Cheers!

2022-09-12 05:58 UTC, NathanKell commented
(Note that AIUI no new release is required, just merging the PR will make CKAN recognize it's compatible on the next netkan refresh. 🎉 )

2022-10-02 08:33 UTC, kcziuy commented
KSP_VERSION also needs to be 1.12.3 to be compatible, otherwise crashes mod manager

2022-10-02 08:34 UTC, kcziuy requested changes
KSP_VERSION needs to be changed

2022-10-09 18:38 UTC, NathanKell commented
Fixed. In my experience that wasn't necessary, but maybe it so now so I've made that change.

2022-10-09 18:48 UTC, merged

2022-10-09 19:09 UTC, NathanKell commented
SWEET! Thanks!! :)